import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ABeeZee, Inter, Mulish } from "next/font/google";
import Navbar from "@/components/navigation/nav-bar";
import { NavigationProvider } from "@/context/navigation-context";
import "./globals.css";
import Footer from "@/components/sections/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const abeeZee = ABeeZee({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-abeezee",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const mulish = Mulish({
  subsets: ["latin"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${abeeZee.variable} ${inter.variable} ${mulish.variable} min-h-screen antialiased font-serif`}
      >
        <NavigationProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </NavigationProvider>
      </body>
    </html>
  );
}
